# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsjqaHabz-X6NsHzoMZqVhSrx8azow75
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_baixa = [100, 250, 400, 550, 700, 850, 1000, 1150, 1300, 1450]

X_media = [1700, 1850, 2000, 2150, 2300, 2450, 2600, 2750, 2900, 3050]

X_alta = [2650, 2800, 2950, 3100, 3250, 3400, 3550, 3700, 3850, 4000]

X = []
for valor in X_baixa:
    X.append([valor])
for valor in X_media:
    X.append([valor])
for valor in X_alta:
    X.append([valor])


y = []
for i in range(10):
    y.append(0)
for i in range(10):
    y.append(1)
for i in range(10):
    y.append(2)

X_treino, X_teste, y_treino, y_test = train_test_split(X, y, test_size=0.2)

modelo = DecisionTreeClassifier()
modelo.fit(X_treino, y_treino)

predicoes_treino = modelo.predict(X_treino)
acuracia_treino = accuracy_score(y_treino, predicoes_treino)

predicoes_teste = modelo.predict(X_teste)
acuracia_teste = accuracy_score(y_test, predicoes_teste)

print(f"Nota no treino (Simulado): {acuracia_treino * 100:.2f}%")
print(f"Nota no teste (Prova Real): {acuracia_teste * 100:.2f}%")

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = load_iris()
X = iris.data
y = iris.target
test_size = 0.2

X_treino, X_teste, y_treino, y_teste = train_test_split( X, y, test_size=test_size)

# Árvore de decisão
arvore = DecisionTreeClassifier()
arvore.fit(X_treino, y_treino)

pred = arvore.predict(X_teste)
acc_arvore = accuracy_score(y_teste, pred)

# KNN
knn = KNeighborsClassifier()
knn.fit(X_treino, y_treino)

pred = knn.predict(X_teste)
acc_knn = accuracy_score(y_teste, pred)

print(f"Acurácia Árvore: {acc_arvore*100:.2f}%")
print(f"Acurácia KNN: {acc_knn*100:.2f}%")