# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsjqaHabz-X6NsHzoMZqVhSrx8azow75
"""

import sys
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_baixa = [100, 250, 400, 550, 700, 850, 1000, 1150, 1300, 1450]

X_media = [1700, 1850, 2000, 2150, 2300, 2450, 2500, 2600, 2700, 2950]

X_alta = [3000, 3050,3100 , 3200, 3250, 3400, 3550, 3700, 3850, 4000]

X = []
for valor in X_baixa:
    X.append([valor])
for valor in X_media:
    X.append([valor])
for valor in X_alta:
    X.append([valor])


y = []
for i in range(10):
    y.append(0)
for i in range(10):
    y.append(1)
for i in range(10):
    y.append(2)

X_treino, X_teste, y_treino, y_test = train_test_split(X, y, test_size=0.2)

modelo = DecisionTreeClassifier()
modelo.fit(X_treino, y_treino)

valor_recebido = int(sys.argv[1])
predicao = modelo.predict([[valor_recebido]])

print(predicao[0])
